#!/usr/bin/env bash

# Script name: dm-ip
# Description: Get IP from interface or external.
# Dependencies: dmenu, fzf, rofi, dig, ip, jq
# GitLab: https://www.gitlab.com/dwt1/dmscripts
# License: https://www.gitlab.com/dwt1/dmscripts/LICENSE
# Contributors: Simon Ingelsson
#               Derek Taylor

# Set with the flags "-e", "-u","-o pipefail" cause the script to fail
# if certain things happen, which is a good thing.  Otherwise, we can
# get hidden bugs that are hard to discover.
set -euo pipefail

# shellcheck disable=SC1091
source ./_dm-helper.sh 2>/dev/null || source _dm-helper.sh 2>/dev/null

source_dmscripts_configs

if configs_are_different; then
    echo "$(date): configs are different" >>"$DM_CONFIG_DIFF_LOGFILE"
    sleep 1
fi

main() {
    declare -A _ips

    _external=$(dig +short myip.opendns.com @resolver1.opendns.com)
    _ips[external]="${_external}"

    for _iface in $(ip -4 -j addr | jq -r '.[] |{ name: .ifname, ip: .addr_info[].local} | join(":")'); do
        _ips[${_iface%:*}]="${_iface##*:}"
    done

    selected="$(printf '%s\n' "${!_ips[@]}" | ${MENU} "ips:")"
    [ -z "${selected}" ] && exit 1
    echo "${_ips["${selected}"]}" | cp2cb
    notify-send "IP (in clipboard)" " ${selected}: ${_ips["${selected}"]}"
}

MENU="$(get_menu_program "$@")"
[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main
